version: '3.8'

services:
  sqlserver:
    container_name: apptarea-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Kenia123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app_network

  api:
    container_name: apptarea-api
    build:
      context: .
      dockerfile: src/Presentation/Dockerfile
    ports:
      - "5208:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Tarea;User Id=sa;Password=Kenia123!;TrustServerCertificate=True;
      - Jwt__Key=ClaveJWTSegura1234567890SuperClave!!
      - Jwt__Issuer=AppTarea
      - Jwt__Audience=AppTareaUsuarios
      - Jwt__ExpireMinutes=60
    depends_on:
      - sqlserver
    networks:
      - app_network

  frontend:  # ✅ CORRECTO
    container_name: apptarea-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  sqlserver_data:
